### ISSUE TITLE
with Vundle: server not starting

### ISSUE THREAD

**Issue by shaunlebron** [bhurlow/vim-parinfer#1]
I use Vundle to manage my vim plugins (on a mac).  I'm not sure why the server wasn't starting, but probably has to do with something Vundle-specific that I'm not aware of.  Details below:

---

I added `Plugin "bhurlow/vim-parinfer"` to my `.vimrc` and ran `:PluginInstall`.  But the parinfer server didn't start when opening an existing `test.clj` file.  The `/tmp/parinfer.log` was empty.  After leaving insert mode, the buffer would be erased.

I started the server manually with `node server.js` and set the pid manually in vim with `let g:parinfer_server_pid = ...` and everything worked.  So the only problem is that the server isn't starting.

**Comment by bhurlow** [comment]
Hey @shaunlebron 
I don't use Vundle myself but I will definitely look into this. 

Ideally the server should start when you open a `.clj` (or lisp file of any kind I suppose). If it doesn't start for some reason, we should handle that case somehow. I'll take look!

**Comment by bhurlow** [comment]
@shaunlebron are you using any other clojure vim plugins? I want to make sure the parinfer stuff doesn't collide with other defined mappings etc

**Comment by bhurlow** [comment]
after [redirecting stderr](https://github.com/bhurlow/vim-parinfer/commit/064386e243d1a3d378baf1e10997507feada5e9c) it looks like Vundle doesn't execute the scripts from the same directory as pathogen:

```
Error: Cannot find module '/Users/bh/server.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
module.js:339
    throw err;
    ^
```

**Comment by shaunlebron** [comment]
thanks, working!
