### ISSUE TITLE
Select_full_form() not working

### ISSUE THREAD

**Issue by kovacnica** [bhurlow/vim-parinfer#11]
Hi,

I've followed instructions for installation from README.md, but plugin wasn't working.

It seams that current commit doesn't publish g:Select_full_from() as global function. When i removed g: from function declaration plugin stopped throwing errors.

Current fn declaration:

function! Select_full_form()
    let starting_line = line('.')
    let top_empty = 0
    let bottom_empty = 0
...

Can you look into this...

**Comment by bhurlow** [comment]
hi @kovacnica, can you paste me the error you're seeing? I believe `Select_full_form` to be working although it crudely selects the full form by looking for whitespace lines above and below the cursor so it doesn't work on a form that has a blank line *inside* of it.

for example, a form like this wouldn't work with the current code:

```clj
(defn foo [x]
  (do
    (println x)

    (another-thing x))
```

**Comment by kovacnica** [comment]
Sure, no problem....

*Error message:*
Error detected while processing function <SNR>64_send_buffer:
line   11:
E117: Unknown function: Select_full_form
Press ENTER or type command to continue
Error detected while processing function <SNR>64_send_buffer:
line   11:
E15: Invalid expression: Select_full_form()
Error detected while processing function <SNR>64_send_buffer:
line   12:


And regarding above example... It works flawlessly when above error is not
occuring. That is when *g:  *is not present.

In attachment you can find *parinfer.vim *file with local modifications. I
think that it would be good thing to look into supporting cljc, and cljs
files also.

Anyway I like the Parinfer idea, and appreciate your work.

Regards,

On Mon, Dec 28, 2015 at 6:36 PM, Brian Hurlow <notifications@github.com>
wrote:

> hi @kovacnica <https://github.com/kovacnica>, can you paste me the error
> you're seeing? I believe Select_full_form to be working although it
> crudely selects the full form by looking for whitespace lines above and
> below the cursor so it doesn't work on a form that has a blank line
> *inside* of it.
>
> for example, a form like this wouldn't work with the current code:
>
> (defn foo [x]
>   (do
>     (println x)
>
>     (another-thing x))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bhurlow/vim-parinfer/issues/11#issuecomment-167608892>
> .
>



-- 
-----------------------------------------------------------------
dipl. ing. Robert Geršak

Address:     Nikole Bonifačića 13, Velika Gorica
Mob.:        +385 99 8155 267
Tel.:          +385 1 6221 831

**Comment by bhurlow** [comment]
ok yea that definitely looks like a scoping bug. Vim is so weird about stuff like that. I'll fix it asap

**Comment by bhurlow** [comment]
@kovacnica I just encountered this issue on a fresh machine, fixed it by ensure I had node installed and that I ran `npm install` in the vim-parinfer directory

**Comment by kovacnica** [comment]
I'm very new to vim scripting... I've been using vim for about 5 years now,
but never done any scripting.

For now all I can say for shure is that tpope's plugins are the shit. I'm
mean it in the good way. Best possible. So I've been going through some of
his code and throughout some of his plugins he is always using following
naming schema.

plugin#function_name(args...)

So I've quickly refractored vim-parinfer.vim and it works. You can see code
changes @
https://github.com/kovacnica/vim-parinfer/blob/master/plugin/parinfer.vim

Once again... I haven't been hacking vim at all, so I don't have
what/why/when experience. But vim-parinfer.vim code just doesn't feel like
a plugin code at the moment. I mean no disrespect.

P.S. Staring vim starts vim-parinfer and vim-parinfer always starts
parinfer server at port 8088 it is not possible to start another vim
instance with vim-parinfer functionality since send_buffer functionaliy
depends on g:parinfer_server_pid. It should depend on
g:parinfer_server_reachable. vim-parinfer should always start server if it
hasn't always been started. But then I don't know how to close server. Is
that even a problem :) closing a server...?

Kind regards,

On Fri, Jan 8, 2016 at 12:43 PM, Brian Hurlow <notifications@github.com>
wrote:

> @kovacnica <https://github.com/kovacnica> I just encountered this issue
> on a fresh machine, fixed it by ensure I had node installed and that I ran npm
> install in the vim-parinfer directory
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bhurlow/vim-parinfer/issues/11#issuecomment-170070772>
> .
>



-- 
-----------------------------------------------------------------
dipl. ing. Robert Geršak

Address:     Nikole Bonifačića 13, Velika Gorica
Mob.:        +385 99 8155 267
Tel.:          +385 1 6221 831

**Comment by bhurlow** [comment]
haha yea I've been using vim forever but am pretty new to scripting vim as well. 
I'm definitely a member of the cult of tpope ;) 

As far as the sort of vim fn "namespacing" is concerned, I don't really have strong feelings as long as everything works. I've noticed people use the `plugin` prefix for functions that a user may want to remap themselves and `s:` prefix for script local functions. 

I've found that with vim scripting in particular you have to approach things with a bit less rigor than other 'real' languages. VimL has millions of flaws and is ancient so my standards for vim code are a lot lower than other legit languages.

Wanna put together a PR of those changes you added?

as far as the P.S. message is concerned, yes that's a known issue that I haven't fixed yet ;). Issue for that here: https://github.com/bhurlow/vim-parinfer/issues/12

**Comment by kovacnica** [comment]
Sure... Btw what does PR stand for? :D

On Sun, Jan 10, 2016 at 12:41 AM, Brian Hurlow <notifications@github.com>
wrote:

> haha yea I've been using vim forever but am pretty new to scripting vim as
> well.
> I'm definitely a member of the cult of tpope ;)
>
> As far as the sort of vim fn "namespacing" is concerned, I don't really
> have strong feelings as long as everything works. I've noticed people use
> the plugin prefix for functions that a user may want to remap themselves
> and s: prefix for script local functions.
>
> I've found that with vim scripting in particular you have to approach
> things with a bit less rigor than other 'real' languages. VimL has millions
> of flaws and is ancient so my standards for vim code are a lot lower than
> other legit languages.
>
> Wanna put together a PR of those changes you added?
>
> as far as the P.S. message is concerned, yes that's a known issue that I
> haven't fixed yet ;). Issue for that here: #12
> <https://github.com/bhurlow/vim-parinfer/issues/12>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bhurlow/vim-parinfer/issues/11#issuecomment-170293839>
> .
>



-- 
-----------------------------------------------------------------
dipl. ing. Robert Geršak

Address:     Nikole Bonifačića 13, Velika Gorica
Mob.:        +385 99 8155 267
Tel.:          +385 1 6221 831

**Comment by bhurlow** [comment]
PR is short for github pull request

**Comment by bhurlow** [comment]
really the issue is: https://github.com/bhurlow/vim-parinfer/issues/27
