### ISSUE TITLE
FYI - Parinfer now available in Vimscript

### ISSUE THREAD

**Issue by oakmac** [bhurlow/vim-parinfer#15]
The core Parinfer algorithm is now available as a Vimscript library: https://github.com/oakmac/parinfer-viml

**Comment by bhurlow** [comment]
yooooooooo that's awesome. @oakmac Do you have a feel for how the performance compares in Viml? I 'll start a branch to try it out

**Comment by oakmac** [comment]
I have no idea :)

[Issue #3](https://github.com/oakmac/parinfer-viml/issues/3) on the parinfer-viml repo is set up to track performance.

**Comment by bhurlow** [comment]
sounds good. I don't really know very much about bechmarking vim code tbh. will be interesting to find out

**Comment by oakmac** [comment]
I suspect it will be slower than parinfer.js, but unless it is dramatically slower I'm sure it will be simpler to integrate Vimscript than having to deal with the whole node.js/rpc setup.

There are also [performance hacks](https://github.com/oakmac/atom-parinfer#known-limitations) you can use in the extension code to speed things up.

**Comment by bhurlow** [comment]
I also suspect it'll be slower and saner

**Comment by oakmac** [comment]
I'm excited to see what you can come up with here :+1:

**Comment by bhurlow** [comment]
yea I've actually been surprised how smooth the RPC approach has been. It definitely has a few bugs in there but I use it *heavily*. parfiner is a great idea

**Comment by oakmac** [comment]
> The idea of parinfer trumps any implementation details

Strongly agree

**Comment by bhurlow** [comment]
@oakmac another options here would be to write the parinfer port in python which vim "natively" supports. thoughts? I still plan to give the raw viml a shot

**Comment by bhurlow** [comment]
I figure you've already ported parinfer to like 1000 languages already so whats one more :)

**Comment by bhurlow** [comment]
for that matter ruby is also something we could consider

**Comment by oakmac** [comment]
[parinfer.py](https://github.com/oakmac/parinfer.py) is ready to go :)

**Comment by oakmac** [comment]
I was thinking about this over the weekend. Isn't the case that 99% of vim installations have Python "built-in"? If so, you could ship parinfer.py with the plugin and use it when Python is available. Else it could fall back to the vimscript version.

**Comment by bhurlow** [comment]
yea, not sure really about which versions of vim are floating around out there but I'd say the python extension is now pretty common. Lots of key vim plugins require the python extension (like vim-fireplace even) so depending on it doesn't seem like it would exclude many users

**Comment by bhurlow** [comment]
that was fast!

**Comment by oakmac** [comment]
parinfer.py was the first parinfer port ;)

started back in December for the [sublime-text-parinfer](https://github.com/oakmac/sublime-text-parinfer) plugin

**Comment by shaunlebron** [comment]
this is great, I didn't know python was natively supported by vim.  the viml port was so slow

**Comment by bhurlow** [comment]
Added the viml implementation! 🌻
