### ISSUE TITLE
Getting unwanted whitespace at end of line occassionally

### ISSUE THREAD

**Issue by metasoarous** [bhurlow/vim-parinfer#18]
Not sure exactly why; might be me being clutzy as I learn the tool... If I manage to clarify what's actually causing this I'll share.

**Comment by metasoarous** [comment]
I see... when I start to enter something at the end of an s-exp but end up inserting a space and nothing else before leaving insert mode, it pushes the space out after the paren... which seems reasonable enough.

**Comment by shaunlebron** [comment]
Hi @metasoarous, can you reproduce the behavior in the canonical parinfer editor?
http://shaunlebron.github.io/parinfer/demo

I fixed that behavior some time ago, but it looks like vim-parinfer is using an older version of parinfer.js

**Comment by metasoarous** [comment]
Ah... I see. No, I'm not getting behavior on the canonical version.

**Comment by bhurlow** [comment]
@shaunlebron @metasoarous yes vim-parinfer needs an upgrade. Planning to use the python bindings
