### ISSUE TITLE
visual mode key bindings?

### ISSUE THREAD

**Issue by metasoarous** [bhurlow/vim-parinfer#19]
Are there are recommended set of visual key bindings to indent/unindent multiple lines? Or should the mappings be roughly the same?

**Comment by metasoarous** [comment]
Seems like the same function called in command mode works fine in visual mode, so I'll just use that mapping. I'll for a PR if you feel like adding these mappings as defaults.

**Comment by bhurlow** [comment]
currently I've bound `Tab` and `Shift + Tab` to do indent the line and then balance the form using parinfer. Those binding are simply recommendations from the original parinfer spec, but I've found them to work pretty well with day to day editing

**Comment by metasoarous** [comment]
Sure; I see that's the case in normal/command mode. I'm finding a visual mode mapping convenient though:

```
  autocmd FileType clojure vnoremap <buffer> <Tab> :call parinfer#do_indent()<cr>
  autocmd FileType clojure vnoremap <buffer> <S-Tab> :call parinfer#do_undent()<cr>
```

I don't know what the best way of indenting multiple lines together would be if not this.

**Comment by bhurlow** [comment]
ahhh I see what you're saying now. Let's just add those two `vnoremap` calls, seems like a find addition to me
