### ISSUE TITLE
Error detected while processing VimLeavePre Auto commands (stop_server)

### ISSUE THREAD

**Issue by GoranM** [bhurlow/vim-parinfer#22]
Log shows:

```
Executing VimLeavePre Auto commands for "*.clj"
autocommand call <sid> stop_server()

Error detected while processing VimLeavePre Auto commands for "*.clj":
E129: Function name required
```

I changed the code to call the function correctly:

``` diff
-   autocmd VimLeavePre *.clj,*cljs,*.cljc,*.edn call <sid> stop_server()
+   autocmd VimLeavePre *.clj,*cljs,*.cljc,*.edn call parinfer#stop_server()
```

With this, I got a symbol undefined error for `g:parinfer_server_pid`, and I noticed that the line which was supposed to set it was commented out:

``` viml
let cmd = "node " . g:parinfer_script_dir . "/server.js"  . " &> /tmp/parinfer.log & echo $!"
let pid = system(cmd)
" not sure why it gives 0 all the time: echo "SHELL CMD STATUS CODE" . v:shell_error
" i'd like to detect of the server command returns an error code
"let g:parinfer_server_pid = pid
```

On my system, the `system(cmd)` call returns the correct pid, so I uncommented the `let g:parinfer_server_pid = pid` line, and that worked perfectly.

I don't know if system(cmd) returning 0 is a common issue, or if it was maybe just an issue with the developer's system, but it's probably not a good idea to leave things as they are, where users get this error, and where a process that is no longer being used continues to exist on the system.

**Comment by bhurlow** [comment]
fixed with vimscript impl

**Comment by MaiUlShajar** [comment]
@GoranM shame on you for selling yourself as a cheap slave. Shame on you for saying that disgusting and racist and arrogant word before the name "frev", in your BGE outline shader tutroial. You are a big worthless loser Goran. DEATH to everyone who uses those words. DEATH to "univeristies". DEATH to the disgusting and garbage so called "health sector". DEATH TO LOSERS WHO USE STUPID "TITLES". SHAME ON YOU @GoranM
