### ISSUE TITLE
Lisp variant-specific indent

### ISSUE THREAD

**Issue by bpstahlman** [bhurlow/vim-parinfer#23]
Given that Parinfer knows nothing about the lisp variant-specific indentation conventions... Is the "parinfer way" to ignore such conventions, contenting oneself with a shiftwidth-based indentation, which satisfies parinfer's invariant without conforming to any particular lisp style guide? Or is the idea that you should always use parinfer in conjunction with a variant-specific plugin that understands the lisp variant's indentation preferences? And if it's the latter, how would it work? Intuitively, I would think that the variant-specific plugin would handle indents/dedents and then pass the resulting text to indentParinfer() to adjust the parens. But while reading the section "Adding Parinfer to an Editor" on the npmjs site, I saw this:

- Use Tab Stops to allow the user to quickly indent/dedent lines to important points in Indent Mode. When the user presses Tab or Shift+Tab, do the following:
    - *Prevent Tab from doing its normal space insertion, or just remove them prior to the next step.*
    - Run Indent Mode on the text, passing the cursor in as normal. BUT, if you have multiple lines selected, you must instead pass in the starting position of the selection as the cursor.

__Question:__ If we don't add any tabs/spaces prior to the call to indentMode, how will the correct parens be calculated? Or am I misunderstanding what is meant by "Prevent Tab from doing its normal space insertion"? E.g., perhaps it simply means don't allow tab to be converted to spaces?

Is this project meant to be used in conjunction with lisp variant-specific indent plugins, or standalone?

**Comment by shaunlebron** [comment]
@bpstahlman can you move this question to https://github.com/shaunlebron/parinfer?
