### ISSUE TITLE
Copy-paste bug

### ISSUE THREAD

**Issue by tomaskulich** [bhurlow/vim-parinfer#31]
```
function! parinfer_lib#ParenMode(text, options)
  let l:result = s:ProcessText(a:text, s:INDENT_MODE, a:options)
  return s:PublicResult(l:result)
endfunction
```

there should probably be
```
  let l:result = s:ProcessText(a:text, s:PAREN_MODE, a:options)
```

**Comment by bhurlow** [comment]
@tomaskulich ok cool, what does this have to do with copy/paste?

**Comment by bhurlow** [comment]
https://github.com/bhurlow/vim-parinfer/issues/34

**Comment by tomaskulich** [comment]
I just thought it was created when copy-pasting the code since the exact snippet is just above this one.

**Comment by bhurlow** [comment]
ohh haha just read it. ok, let's add a hook for both modes in https://github.com/bhurlow/vim-parinfer/issues/34
