### ISSUE TITLE
Support configurable extensions

### ISSUE THREAD

**Issue by RhysU** [bhurlow/vim-parinfer#54]
Any way to have https://github.com/bhurlow/vim-parinfer/blob/master/plugin/parinfer.vim#L154 not require hardcoded extensions?  I'm working with some .sls, .scm, .sld stuff at the moment.  Hate to hack up the vim-parinfer source vs just setting some configurable flag.  I suspect the logic looks something like https://stackoverflow.com/questions/27213808/use-variables-lists-as-an-autocmd-pattern, but I don't know VimScript well enough to grok that SO answer.

**Comment by bhurlow** [comment]
yea, silly to have to PR for each extension type :) 

I think we may be able to define a global setting such as `let g:parinfer_file_types = 'cljs,edn'` and iterate over those values to generate the `autocmd`, not sure yet how to pass a string value to the `autocmd` literal, maybe with `execute`

**Comment by RhysU** [comment]
I believe the right idiom is https://stackoverflow.com/questions/27592949/using-a-variable-as-the-subject-of-autocmd-filetype.  The right way to have overriddable defaults may be https://github.com/vim-syntastic/syntastic/blob/9e1b2a8620a0ff48a9f4e42a6e09b65a34ad2a6a/plugin/syntastic.vim#L84.
